<?php

namespace RainLoop\Enumerations;

class Capa
{
	const OPEN_PGP = 'OPEN_PGP';
	const PREFETCH = 'PREFETCH';
	const THEMES = 'THEMES';
	const USER_BACKGROUND = 'USER_BACKGROUND';
	const SIEVE = 'SIEVE';
	const ATTACHMENT_THUMBNAILS = 'ATTACHMENT_THUMBNAILS';
	const ADDITIONAL_ACCOUNTS = 'ADDITIONAL_ACCOUNTS';
	const IDENTITIES = 'IDENTITIES';
	const COMPOSER = 'COMPOSER';
	const CONTACTS = 'CONTACTS';
	const RELOAD = 'RELOAD';
	const SEARCH = 'SEARCH';
	const SEARCH_ADV = 'SEARCH_ADV';
	const SETTINGS = 'SETTINGS';
	const QUOTA = 'QUOTA';
	const HELP = 'HELP';
	const TEMPLATES = 'TEMPLATES';
	const MESSAGE_ACTIONS = 'MESSAGE_ACTIONS';
	const MESSAGELIST_ACTIONS = 'MESSAGELIST_ACTIONS';
	const ATTACHMENTS_ACTIONS = 'ATTACHMENTS_ACTIONS';
	const DANGEROUS_ACTIONS = 'DANGEROUS_ACTIONS';
	const AUTOLOGOUT = 'AUTOLOGOUT';
}
