<?php

namespace RainLoop\Enumerations;

class Capa
{
	const PREM = 'PREM';
	const TWO_FACTOR = 'TWO_FACTOR';
	const TWO_FACTOR_FORCE = 'TWO_FACTOR_FORCE';
	const OPEN_PGP = 'OPEN_PGP';
	const PREFETCH = 'PREFETCH';
	const GRAVATAR = 'GRAVATAR';
	const THEMES = 'THEMES';
	const USER_BACKGROUND = 'USER_BACKGROUND';
	const SIEVE = 'SIEVE';
	const FILTERS = 'FILTERS';
	const ATTACHMENT_THUMBNAILS = 'ATTACHMENT_THUMBNAILS';
	const ADDITIONAL_ACCOUNTS = 'ADDITIONAL_ACCOUNTS';
	const TEMPLATES = 'TEMPLATES';
	const AUTOLOGOUT = 'AUTOLOGOUT';
}
